version: '2.4'
services:
  mongo:
    image: sudachen/mongo-db:latest
    container_name: mongo4
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
      - "172.17.0.1:27017:27017"
    volumes:
      - ${HOME}/Mongo4/db:/data/db:Z
      - ${HOME}/Mongo4/configdb:/data/configdb:Z

