#!/bin/bash

docker-compose -f docker-compose.yml --project-directory . down

mkdir -p db
mkdir -p configdb
docker-compose -f docker-compose.yml --project-directory . up --build -d
docker container prune -f
docker image prune -f
